### ISSUE TITLE
Everytime you open the modal, another set of source options are appended

### ISSUE THREAD

**Issue by sgtpenguin** [filestack/filestack-react#103] opened 2020-11-12 15:30 UTC
To reproduce:  Open the file picker, close it, then open it again.  You can see every time a new set of source options (local,link,facebook,etc.) are appended to the bar on the left
<img width="866" alt="Screen Shot 2020-11-12 at 10 29 48 AM" src="https://user-images.githubusercontent.com/16600959/98960104-ff01b980-24d1-11eb-8b83-e2a9ffba05e7.png">

**Comment by brunopopf** [comment] 2020-11-22 17:10
Same problem...

**Comment by anixonCatalyst** [comment] 2020-12-07 21:29
I am running into the same issue, is there a workaround for this?

**Comment by jakubpeksa** [comment] 2020-12-08 05:51
Can you provide codepen? I cannot reproduce that on demo

**Comment by sgtpenguin** [comment] 2020-12-08 14:15
I can't reproduce it on the demo you provided either, but it's hard to play with it because it's minified and uses compiled code.  When I try to make [my own codepen](https://codepen.io/sgtpenguin/pen/wvzWQjm) I cannot successfully import the library.  I get an error:

 `Uncaught Error: [Package Error] "punycode" does not exist. (Imported by "node:punycode").`

@jakubpeksa Can you please provide a working codepen demo that imports the package from NPM and uses jsx syntax and I will try to reproduce the issue?

**Comment by anixonCatalyst** [comment] 2020-12-08 15:37
@jakubpeksa 
I had the same issue when trying to get this working with react, but I can duplicate the issue using plain JS. The problem seems to be limited to calling open on the same instance of the picker multiple times.

[example here](https://codepen.io/anixoncatalyst/pen/rNMLPMY)

**Comment by jakubpeksa** [comment] 2020-12-08 16:05
Regarding punycode error - I'll check it out tomorrow but I can't run it now also - that should be fixed with the newest 4.0.0 filestack-react version which will use the newest react, it'll be deployed within a month and I'll keep you updated about that.
@anixonCatalyst Thanks for example! That looks like filestack-js core library problem which you can report here https://github.com/filestack/filestack-js/issues

**Closed as completed** 2020-12-16 11:18 UTC
