### ISSUE TITLE
Server side rendering problem

### ISSUE THREAD

**Issue by ZeroCho** [filestack/filestack-react#9] opened 2017-04-07 04:29 UTC
After changing code from
`const filestack = require('filestack-js').default`

from
`import filestack  from 'filestack-js';`

Following issue happens when I try to render a component with **react-filestack** on the server
`ReferenceError: File is not defined`

Because there is no File object in the server, this component cannot import filestack-js on the server.
That is why I didn't **import 'filestack-js'**, but **require('filestack-js').default** inside the click handler which only renders in client,

**Comment by samuxyz** [comment] 2017-04-07 15:30
Interesting discovery @ZeroCho, I am going to throw this problem to the dev team asap! Btw, if you just `require('filestack-js')` it works?

**Comment by ZeroCho** [comment] 2017-04-07 15:49
It should be inside the click event handler, so that it is only rendered in client. Look [here](https://github.com/filestack/react-filestack/blob/8994e0511b7bc09acbf68b06b930103d2700549d/src/ReactFilestack.jsx#L32)

**Comment by samuxyz** [comment] 2017-04-07 16:11
I just found out this thread http://stackoverflow.com/questions/33704714/cant-require-default-export-value-in-babel-6-x

I am not sure but perhaps the filestack-js should export in a ES5 style and that would not cause problems by running `import filestack ...`. At the moment the guys exports filestack with `export default`.

Gonna tell them.

**Comment by samuxyz** [comment] 2017-04-07 16:14
@ZeroCho yeah ive seen the old code but i wished it could be solved without tricks like that.

**Comment by ZeroCho** [comment] 2017-04-30 09:08
@samuxyz Any recent news about this? I'm thinking about making separate branch for SSR temporarily. I'm still using v0.5.3 due to this problem.

**Comment by velveteer** [comment] 2017-04-30 20:11
@ZeroCho I think the next release of filestack-js should resolve this issue*. I will let you know when that lands.

*Meaning fixing the root cause in filestack-js. I think @samuxyz pushed a fix for this in https://github.com/filestack/react-filestack/commit/bb8a37b3ca8cf9592081f779cc11a7c98e725e87.

**Comment by samuxyz** [comment] 2017-05-01 07:14
@velveteer yes at the moment I reverted to the original `require` from @ZeroCho within the function. I guess I'll close the issue for now.

**Closed as completed by samuxyz** 2017-05-01 07:14 UTC
