### ISSUE TITLE
Feature Request: Add More Callback Functions

### ISSUE THREAD

**Issue by Diasporism** [filestack/filestack-react#31] opened 2017-09-28 18:28 UTC
First of all, thanks for putting together a React component for all of us Filestack users!

As a feature request I'd love to see more optional callbacks such as `onFileUploadProgress` and those listed in https://www.filestack.com/docs/javascript-api/pick-v3.

Is adding any more of these callbacks on the roadmap?

**Comment by samuxyz** [comment] 2017-10-09 04:00
Hey @Diasporism, im sorry for the late response. 
If you want to use any of those functions such as `onFileUploadProgress`, you just have to pass the them in the `options` prop!

Taken from the official documentation (https://www.filestack.com/docs/javascript-api/picker-examples-v3):

```
client.pick({
  uploadInBackground: false,
  hideWhenUploading: true,
  startUploadingWhenMaxFilesReached: true,
  onFileUploadProgress: function(file, progressEvent) {
    console.log(JSON.stringify(progressEvent.totalPercent))
  }
}).then(function(result) {
  console.log(JSON.stringify(result.filesUploaded))
})
```

`onFileUploadProgress` is nothing more than a parameter for `pick`.

**Comment by samuxyz** [comment] 2017-10-09 04:26
Btw, I am going to close it as it's like a duplicate of [#30](https://github.com/filestack/filestack-react/issues/30)

**Closed as completed by samuxyz** 2017-10-09 04:26 UTC
